version: '3'
services:
  zola:
    image: balthek/zola:0.14.0 #Build once
    command: "build"
    working_dir: /home/site
    user: 1001:1001
    volumes:
      - .:/home/site:rw
      - public_files:/home/site/public:rw

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    depends_on:
      - "zola"
    volumes:
      - public_files:/usr/share/nginx/html/:ro
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    
  certbot:
    depends_on:
      - "zola"
    image: certbot/dns-digitalocean
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ~/.secrets/certbot/digitalocean.ini:/creds/digitalocean.ini:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  public_files: