version: "3"
services:
  zola:
    image: balthek/zola:0.14.0 #Build once
    command: "build --output-dir /volume/html"
    working_dir: /site
    privileged: true
    volumes:
      - .:/site:rw
      - public_files:/volume:rw
  nginx-proxy:
    depends_on:
      - "zola"
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy_net
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  acme-companion:
    container_name: nginx-proxy-acme
    networks:
      - cert_net
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - acme:/etc/acme.sh
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=ozerno@protonmail.com
    image: nginxproxy/acme-companion
  #letsencrypt:
   # image: jrcs/letsencrypt-nginx-proxy-companion
    #container_name: encrypt
    #depends_on:
    #  - nginx-proxy
    #volumes:
    #  - $HOME/certs:/etc/nginx/certs:rw
    #  - /var/run/docker.sock:/var/run/docker.sock:ro
    #volumes_from:
    #  - nginx-proxy
    #networks:
    #  - proxy_net
  nginx:
    image: nginx:alpine
    container_name: www.ningunx-presx-por-luchar.info
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/sites-available:/etc/nginx/sites-available"
      - "./docker/nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./docker/nginx/nginxconfig.io/:/etc/nginx/nginxconfig.io/"
      - "$HOME/certs:/etc/letsencrypt/ningunx-presx-por-luchar.info/"
      - "public_files:/usr/share/nginx"
    depends_on:
      - nginx-proxy
      - acme-companion
    environment:
      - VIRTUAL_HOST=www.ningunx-presx-por-luchar.info
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ningunx-presx-por-luchar.info,www.ningunx-presx-por-luchar.info
      - LETSENCRYPT_EMAIL=ozerno@protonmail.com
    networks:
      - proxy_net
      
networks:
  cert_net:
    driver: bridge
  proxy_net:
    driver: bridge

volumes:
  public_files:
  acme:
  certs:
  vhost:
  html: