version: '3'
                                                                   
services:
  reverse-proxy:   
    image: traefik:v2.4                               
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"  # If you run into trouble
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=${LE_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=namecheap"
      - "--certificatesResolvers.myresolver.acme.storage=/certs/acme.json"
      # To avoid rate limits https://letsencrypt.org/docs/rate-limits/
      # when testing it is recommended to use the staging server (issues an invalid cert, but works for testing)
       - "--certificatesResolvers.myresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"      # The HTTP port for internal or http to https redirection
      - "443:443"    # HTTPS traffic
      - "8080:8080"  # The Web UI (enabled by --api.insecure=true)
    volumes:
      - ./certs/:/certs/
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:  
      # REQUIRED key=value format in .env file,
      # Don't set here if you plan on commiting/pushing
      # .gitignore .env and /certs/ for security if you do
      - DO_AUTH_TOKEN   # Change to whichever variable(s) your provider uses
      - YOURDOMAIN
      - LE_EMAIL
    networks:
      - proxy

networks:
  proxy:
    external: true