base_url = "https://www.feria-anarquista-montevideo.info"
compile_sass = true
build_search_index = false
title = "Novena Feria del Libro Anarquista"

taxonomies = [
    { name = "tags", fees = false, paginate_by = 10 },
]

[markdown]
highlight_code = true

[extra]
navbar_items = [
    { code = "es", nav_items = [
        { url = "$BASE_URL/", name = "Inicio" },
        { url = "$BASE_URL/posts", name = "Publicaciones" },
        { url = "$BASE_URL/tags", name = "Etiquetas" },
        { url = "$BASE_URL/ubicacion", name = "Ubicación" },
        { url = "$BASE_URL/crono", name = "Cronograma" },
        { url = "$BASE_URL/contact.html", name = "Contacto" }
    ] },
]

[extra.favicon]
safari_pinned_tab = "/icons/safari-pinned-tab.svg"
webmanifest = "/icons/site.webmanifest"

# Author details
[extra.author]
name = ""
avatar = "images/avatar.png"

# Social links